version: "3.4"
services:

  redis:
    image: redis:alpine

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/db/
        target: /var/lib/postgresql/data

  server:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/loaded_log_cache/
        target: /predict-python/cache/loaded_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/labeled_log_cache/
        target: /predict-python/cache/labeled_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/log_cache/
        target: /predict-python/cache/log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/model_cache/
        target: /predict-python/cache/model_cache/

  scheduler:
    image: nirdizatiresearch/predict-python
    build:
      context: .
    command: python3 manage.py rqscheduler
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/loaded_log_cache/
        target: /predict-python/cache/loaded_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/labeled_log_cache/
        target: /predict-python/cache/labeled_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/log_cache/
        target: /predict-python/cache/log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/model_cache/
        target: /predict-python/cache/model_cache/

  worker:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py rqworker default
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/loaded_log_cache/
        target: /predict-python/cache/loaded_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/labeled_log_cache/
        target: /predict-python/cache/labeled_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/log_cache/
        target: /predict-python/cache/log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/model_cache/
        target: /predict-python/cache/model_cache/
