version: "3.4"
services:

  redis:
    image: redis:alpine

  server:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 80:8000
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/db/
        target: /predict-python/db/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/loaded_log_cache/
        target: /predict-python/cache/loaded_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/labeled_log_cache/
        target: /predict-python/cache/labeled_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/log_cache/
        target: /predict-python/cache/log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/model_cache/
        target: /predict-python/cache/model_cache/

  scheduler:
    image: nirdizatiresearch/predict-python
    build:
      context: .
    command: python3 manage.py rqscheduler
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/db/
        target: /predict-python/db/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/loaded_log_cache/
        target: /predict-python/cache/loaded_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/labeled_log_cache/
        target: /predict-python/cache/labeled_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/log_cache/
        target: /predict-python/cache/log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/model_cache/
        target: /predict-python/cache/model_cache/

  worker:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py rqworker default
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/db/
        target: /predict-python/db/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/loaded_log_cache/
        target: /predict-python/cache/loaded_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/labeled_log_cache/
        target: /predict-python/cache/labeled_log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/log_cache/
        target: /predict-python/cache/log_cache/
      - type: bind
        source: /home/ubuntu/Willo/nirdizati-research/model_cache/
        target: /predict-python/cache/model_cache/
